### PR TITLE
Issue 5

### PR DESCRIPTION
**Pull request by JosiahRegencia**
minor additions for issue #5

### CODE REVIEW

**Comment by greenmoss** [comment]
Please remove all `.pyc` files, and add them to your `.gitignore` file

**Comment by greenmoss** [comment]
Still need to remove the existing `.pyc` files. You can use `git rm file.pyc` to do this.

**Comment by greenmoss** [comment]
`savant/__init__.pyc` 😄

**Comment by JosiahRegencia** [comment]
Finished both issue #6 and issue #5

**Comment by greenmoss** [comment]
Need to merge before closing

**Comment by JosiahRegencia** [comment]
My bad

**Comment by greenmoss** [comment]
No problem; I am reviewing and will merge

**Comment by greenmoss** [comment]
There is one stray `.pyc` file left; please remove it

**Comment by JosiahRegencia** [comment]
finished

**Pull request merged**
